let stock = [
    {
        id: 1,
        img: "./Imagens/Itens.img/pngwing.com.png",
        nome: "Cowboy",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 149.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Chapéus",
    },
    {
        id: 2,
        img: "./Imagens/Itens.img/pngwing.com (1).png",
        nome: "Suede",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicingm! ",
        valor: 199.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Chapéus",
    },
    {
        id: 3,
        img: "./Imagens/Itens.img/pngwing.com (2).png",
        nome: "Leather",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicingm!.",
        valor: 249.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Chapéus",
    },
    {
        id: 4,
        img: "./Imagens/Itens.img/pngwing.com(13).png",
        nome: "Black Hat",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicingm!.",
        valor: 149.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Chapéus",
    },
    {
        id: 5,
        img: "./Imagens/Itens.img/pngwing.com (14).png",
        nome: "White Hat",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicingm!.",
        valor: 149.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Chapéus",
    },
    {
        id: 6,
        img: "./Imagens/Itens.img/pngwing.com (15).png",
        nome: "Peao Black Hat",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicingm!.",
        valor: 290.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Chapéus",
    },
    {
        id: 7,
        img: "./Imagens/Itens.img/pngwing.com (16).png",
        nome: "Compact Bag",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 349.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Bolsas",
    },
    {
        id: 8,
        img: "./Imagens/Itens.img/pngwing.com (17).png",
        nome: "Black Brand",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 2.599,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Bolsas",
    },
    {
        id: 9,
        img: "./Imagens/Itens.img/pngwing.com (18).png",
        nome: "Cambará Model",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 649.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Bolsas",
    },
    {
        id: 10,
        img: "./Imagens/Itens.img/pngwing.com (3).png",
        nome: "Urban",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 449.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Bolsas",
    },
    {
        id: 11,
        img: "./Imagens/Itens.img/pngwing.com (4).png",
        nome: "Waterproof",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 600,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Bolsas",
    },
    {
        id: 12,
        img: "../Imagens/Itens.img/pngwing.com(12).png",
        nome: "Waterproof Urban",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 890.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Bolsas",
    },
    {
        id: 13,
        img: "../Imagens/Itens.img/pngwing.com (20).png",
        nome: "Winter Boots",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 559.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Botas",
    },
    {
        id: 14,
        img: "../Imagens/Itens.img/pngwing.com (19).png",
        nome: "Designer Boots",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 959.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Botas",
    },
    {
        id: 15,
        img: "../Imagens/Itens.img/pngwing.com (5).png",
        nome: "High",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 759.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Botas",
    },
    {
        id: 16,
        img: "../Imagens/Itens.img/pngwing.com (6).png",
        nome: "Leather",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 549.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Botas",
    },
    {
        id: 17,
        img: "../Imagens/Itens.img/pngwing.com (10).png",
        nome: "Women's High",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 1100,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Botas",
    },
    {
        id: 18,
        img: "../Imagens/Itens.img/pngwing.com (7).png",
        nome: "Leather Sheath",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing!",
        valor: 249.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Acessórios",
    },
    {
        id: 19,
        img: "../Imagens/Itens.img/pngwing.com (8).png",
        nome: "knife Sheath",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 49.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Acessórios",
    },
    {
        id: 20,
        img: "../Imagens/Itens.img/pngwing.com (9).png",
        nome: "Basic Hem",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 59.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Acessórios",
    },
    {
        id: 21,
        img: "../Imagens/Itens.img/kisspng-sheath-knife-gun-holsters-scabbard-belt-5b0c89d579c793.3550847515275483734988.jpg",
        nome: "Bainha black",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 89.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Acessórios",
    },
    {
        id: 22,
        img: "../Imagens/Itens.img/download.jpeg",
        nome: "Cama basica",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 499.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Pets",
    },
    {
        id: 23,
        img: "../Imagens/Itens.img/png-transparent-sofa-bed-dog-cat-pet-bed-mattress-furniture-couch.png",
        nome: "Cama de camursa",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 899.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Pets",
    },
    {
        id: 24,
        img: "../Imagens/Itens.img/png-transparent-dog-bed-pet-shop-cama-nido-dog-furniture-animals-rectangle.png",
        nome: "Cama Low P",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 399.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Pets",
    },
    {
        id: 25,
        img: "../Imagens/Itens.img/Conjunto-Peitoral-e-Guia-bananas.png",
        nome: "Black guia",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 159.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Pets",
    },
    {
        id: 26,
        img: "../Imagens/Itens.img/images.jpeg",
        nome: "Guia basica",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 25.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Pets",
    },
    {
        id: 27,
        img: "../Imagens/Itens.img/download (1).jpeg",
        nome: "Sela basica",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 1205.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Selas",
    },
    {
        id: 28,
        img: "../Imagens/Itens.img/download (2).jpeg",
        nome: "Sela MODE",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 2500.90,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Selas",
    },
    {
        id: 29,
        img: "../Imagens/Itens.img/download (3).jpeg",
        nome: "Sela Pers.",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 4000,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Selas",
    },
    
    {
        id: 30,
        img: "../Imagens/Itens.img/png-clipart-wallet-coin-purse-leather-product-design-wallet-brown-leather.png",
        nome: "Carteira de couro",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 149.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 31,
        img: "../Imagens/Itens.img/png-transparent-wallet-leather-wallet-angle-brown-leather.png",
        nome: "Carteira Pers.",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 144.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 32,
        img: "../Imagens/Itens.img/pngegg.png",
        nome: "Carteira de couro",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 24.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 33,
        img: "../Imagens/Itens.img/png-transparent-bracelet-leather-jewellery-fossil-group-steel-jewellery-miscellaneous-bracelet-leather.png",
        nome: "Pulseira MODE",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 45.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 34,
        img: "../Imagens/Itens.img/png-transparent-bracelet-leather-jewellery-trendjuwelier-watch-jewellery-miscellaneous-bracelet-leather.png",
        nome: "Pulseira Pers.",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 149.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 35,
        img: "../Imagens/Itens.img/pngwing.com (11).png",
        nome: "Pulseira p/relogio",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 49.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 36,
        img: "../Imagens/Itens.img/png-transparent-belt-leather-united-kingdom-jeans-suede-belts-brown-company-leather.png",
        nome: "Cinto de couro",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 89.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 37,
        img: "../Imagens/Itens.img/21884-2-case-couro-com-suporte-de-cartao-marrom.png",
        nome: "Capa de couro IP8",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 89.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 38,
        img: "../Imagens/Itens.img/png-transparent-apple-iphone-x-silicone-case-apple-smart-case-for-9-7-inch-ipad-pro-apple-iphone-x-leather-case-others-brown-orange-mobile-phone-case-thumbnail.png",
        nome: "Capa de couro IP10",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 99.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
    {
        id: 39,
        img: "../Imagens/Itens.img/21882-case-couro-com-suporte-de-cartao-marrom.png",
        nome: "Capa Pers.",
        descript: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
        valor: 149.99,
        sizes: ['P', 'M', 'G'],
        adicionar: "Adicionar ao carrinho",
        tag: "Outros",
    },
];